server:
  port: 8080
spring:
  application:
    name: flightApi
  datasource:
    url: jdbc:mysql://xxxx:xxxx/xxxx
    username: xxxx
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
