server:
  port: 8080
spring:
  application:
    name: flightApi
  web:
    resources:
      static-locations:
        - file:/Users/xieyongli/Documents/GitHub/FullStack25Q2/flight-client/dist
  datasource:
    url: jdbc:mysql://xxxx:xxxx/xxxx
    username: xxxx
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
