insert into company(company_id,name_en,name_cn) values
('CZ','China Southern Airlines Company Limited','中国南方航空'),
('MU','China Eastern Air Holding Company','中国东方航空'),
('CA','Air China Limited','中国国际航空'),
('HU','Hainan Airlines Holding Co., Ltd.','海南航空'),
('3U','Sichuan Airlines Co., Ltd','四川航空'),
('HO','Juneyao Airlines Co., Ltd','吉祥航空');

insert into airport(airport_id,code,name,city) values
(1,'bja','北京A','北京'),
(2,'sha','上海A','上海'),
(3,'TJ','天津','天津'),
(4,'CQ','重庆','重庆'),
(5,'HEB','哈尔滨','哈尔滨'),
(6,'CC','长春','长春'),
(7,'SY','沈阳','沈阳'),
(8,'SJZ','石家庄','石家庄'),
(9,'LZ','兰州','兰州'),
(10,'XN','西宁','西宁'),
(11,'XA','西安','西安'),
(12,'ZZ','郑州','郑州'),
(13,'JN','济南','济南'),
(14,'TY','太原','太原'),
(15,'HF','合肥','合肥'),
(16,'WH','武汉','武汉'),
(17,'CS','长沙','长沙'),
(18,'NJ','南京','南京'),
(19,'CD','成都','成都'),
(20,'GY','贵阳','贵阳'),
(21,'KM','昆明','昆明'),
(22,'HZ','杭州','杭州'),
(23,'NC','南昌','南昌'),
(24,'GZ','广州','广州'),
(25,'FZ','福州','福州'),
(26,'TB','台北','台北'),
(27,'HK','海口','海口'),
(28,'WLMQ','乌鲁木齐','乌鲁木齐'),
(29,'HHHT','呼和浩特','呼和浩特'),
(30,'YC','银川','银川'),
(31,'NN','南宁','南宁'),
(32,'LS','拉萨','拉萨'),
(33,'XG','香港','香港'),
(34,'AM','澳门','澳门'),
(35,'bjb','北京B','北京'),
(36,'shb','上海B','上海')

insert into flight(flight_id,
flight_number,
company_id,
departure_airport_id,
destination_airport_id,
departure_date,
departure_time,
destination_date,
destination_time,
stop_over,
price) values
(1,'F001','CA',1,2,'2025-07-01','13:00','2025-07-02','09:00','',1234),
(2,'F002','HO',2,1,'2025-07-05','08:00','2025-07-06','15:00','9,4',856)
